# Generated by Django 5.1.7 on 2025-04-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasemate_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasemateuser',
            name='username',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
