# Generated by Django 5.1.7 on 2025-04-16 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('roomDetails', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('houseType', models.CharField(choices=[('Flat', 'Flat'), ('Main House', 'Main House'), ('Cottage', 'Cottage'), ('Bachelor', 'Bachelor'), ('Other', 'Other')], max_length=50)),
                ('numberOfRooms', models.IntegerField()),
                ('painted', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('ceiling', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('electricity', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('solar', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('durawalled', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('fenced', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rent_images/')),
                ('rent_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentals.rentlisting')),
            ],
        ),
    ]
